### ISSUE TITLE
Move cluster code to `src/`

### ISSUE THREAD

**Issue by zuiderkwast** [valkey-io/libvalkey#14]

**Comment by mkmkme** [comment]
Could you assign it to me please?

**Comment by bjosv** [comment]
I would be happy if we could merge the changes we have in the renaming branch first before we move.
What do you think?

**Comment by mkmkme** [comment]
Sure thing! I asked for that just to keep track of tasks in the backlog :)

**Comment by zuiderkwast** [comment]
@mkmkme Let's create some issues for things you found in #15 that would be good to fix later.

**Comment by bjosv** [comment]
Closed by #15
