### ISSUE TITLE
Don't use Redis as project name in new files license text

### ISSUE THREAD

**Issue by zuiderkwast** [valkey-io/libvalkey#48]
We should not create new files with a license mentioning Redis as the name of the project. Let's change this in a follow-up.

A trademark-neutral version of the license mentions "the copyright holder" here instead of Redis.

_Originally posted by @zuiderkwast in https://github.com/valkey-io/libvalkey/pull/47#discussion_r1677478572_

**Comment by zuiderkwast** [comment]
@michael-grunder ACK?

**Comment by michael-grunder** [comment]
Apologies, I was focused on the code and didn't look closely at the copyright header.  Will open a PR to normalize.

**Comment by zuiderkwast** [comment]
> Have we actually picked an exact license?

Not sure, but Valkey uses bsd-3-clause with "the copyright holder" for new code. It's the default text on open-source initiative's page about this license.
